name: Test Suite
on:
  release:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:14.18.1

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            v1-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
            v1-${{ runner.os }}

      - name: Install Packages
        run: npm install

      - name: Tests
        run: npm test
